### ISSUE TITLE
API gateway?

### ISSUE THREAD

**Issue by phungleson** [poem-web/poem-gateway#1]
Hi Sunli,

Is this repo meant to be an API gateway? Do you have any thoughts on developing it?

Cheers,

**Comment by sunli829** [comment]
> Hi Sunli,
> 
> Is this repo meant to be an API gateway? Do you have any thoughts on developing it?
> 
> Cheers,

I just want to do something like this, but I don't have enough time. 🙂

**Comment by phungleson** [comment]
Yeah I am looking for an api gateway solution but it seems like there isn't any good option in Rust yet.

Most common ones are in C or Go. People want lots of features in API gateway these days so it can be a daunting task to break down the requirements, determining selling points and planing out what to do first.

I am happy to get involved even just to do some research work to get this up and running.

I am looking forward to a solution in Rust!

**Comment by sunli829** [comment]
I would be happy if someone would come with me to do this project. 🙂

**Comment by sunli829** [comment]
I have some other ideas about this project, if you want we can start to redo it together. 😀

**Comment by phungleson** [comment]
Cool let me quickly flip through the code to understand the current state, cheers

**Comment by phungleson** [comment]
Okay I have checked through the code, looks like it comprises of 3 main ideas:

* Listener: where gateway listen for incoming requests
* Plugin: where gateway does something to the request, such as rate limiting or basic auth.. (how is it different from middleware though?)
* Target: where gateway direct the request to somewhere else

`config.yaml` is probably where all things are defined (seems to allow hot-reload).

I am not updated with all the gateway development so just curious if this design is based on some prior work? Probably a good refresher for me to checkout.

**Comment by sunli829** [comment]
I can only start this project after I have finished my work, which may take a few more weeks. 🙂

**Comment by phungleson** [comment]
Close due to lacks of interest and time
